import './globals.css';

import Footer from '@/components/Footer/Footer';
import type { Metadata } from 'next';
import Navbar from '@/components/Navbar/Navbar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className='!scroll-smooth'>
			<body className='flex min-h-dvh flex-col font-sans'>
				<Navbar />
          {children}
				<Footer />
			</body>
		</html>
	);
}
