import './globals.css';

import { CartProvider } from '@/components/CartProvider/CartProvider';
import Footer from '@/components/Footer/Footer';
import type { Metadata } from 'next';
import Navbar from '@/components/Navbar/Navbar';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className='!scroll-smooth'>
			<body className='flex min-h-dvh flex-col font-sans'>
        <CartProvider>
          <Navbar />
            {children}
          <Footer />
        </CartProvider>
			</body>
		</html>
	);
}
